### ISSUE TITLE
SSE connection closed after 1 min 35s

### ISSUE THREAD

**Issue by TitaneBoy** [sguiheux/EventSource#10]
Hello @sguiheux . I was testing your package and I think there is an issue... Somehow, it looks that connection is closed by your package after aroud 1 minute and 35 secs. I've tested my same code with another library I had before and the connection is never closed. The reason I've dropped my old other eventsource package is because it is not working anymore with Angular 6. Your package seems to work (thank you for that :-) ), but it seems to have a timeout somewhere that closes the connection. 

Can you please confirm me if I am right or wrong ?

I was testing your package with an url (of mine) that continuously sends data with no interruption. But as I said previously, the connection was closed after 1 min 35 sec, and it was not by the server.

Thanks in advance for your answer...:-)

**Comment by sguiheux** [comment]
Hello @TitaneBoy 
This is an old fork from AlexGalays/EventSource and I do not add something like this.
https://github.com/sguiheux/EventSource/blob/master/eventsource.js#L158 : if no connectionTimeout set, it should be ok

I already have some problem with this condition (around charOffset part) : https://github.com/sguiheux/EventSource/blob/master/eventsource.js#L366

In another project, I made some changes, js file is here: https://github.com/ovh/cds/blob/master/ui/src/assets/worker/eventsource.js
Is it possible for you to take it and test?  If the problem disapears I will update the lib.

If you can't test with this file, I can publish a special version containing the change.
Let me know what you prefer

FYI: The reason I duplicate the file is that now I do not use it directly in Anguar but in a (webWorker/sharedWorker)

**Comment by TitaneBoy** [comment]
Hi @sguiheux ... I took the content of your eventsource file ( [https://github.com/ovh/cds/blob/master/ui/src/assets/worker/eventsource.js](https://github.com/ovh/cds/blob/master/ui/src/assets/worker/eventsource.js) ) and I replace the content of the old one with it (Copy-Paste). Unfortunetly, when my application calls `const eventSource = new EventSourcePolyfill('https://localhost/webclientapi/livessereadings', {});`, it shows an error:

![image](https://user-images.githubusercontent.com/15614466/42906539-66cd1dc2-8aa9-11e8-9a34-7fe765b04148.png)

I'm not sure If I've done something wrong (i.e If my way to test your file is correct) or if the file has an issue

I've just made a file compare between the 2 files and I saw this:

![image](https://user-images.githubusercontent.com/15614466/42906854-37c77c38-8aaa-11e8-94f2-88861a19b2ed.png)

I think it can explain why it says, in the error, that EventSourcePolyfill is not a constructor...The new file has a missing export..

I added the missing export at the end of the new file and it looks to work very well (Comme un charme :-) )... I didn't have any timeout after 1 min 35 sec...

**Comment by TitaneBoy** [comment]
Hi @sguiheux. Your solution (the changes made to [https://github.com/ovh/cds/blob/master/ui/src/assets/worker/eventsource.js](https://github.com/ovh/cds/blob/master/ui/src/assets/worker/eventsource.js)) seems to works and seems to fix the issue.

Do you think you could release soon a new version to npm with the fix ?

Thank you in advance :-)

**Comment by sguiheux** [comment]
Ok, I will try to do it tomorrow

**Comment by sguiheux** [comment]
I just release 1.0.11 with the fix.
Let me know if it's ok on your side

**Comment by TitaneBoy** [comment]
@sguiheux : Thank you for your help and your great support...It seems now to work well :-)
