### ISSUE TITLE
Add ability to modify EventSourceInit

### ISSUE THREAD

**Issue by PapaNappa** [sguiheux/EventSource#17]
We use a JWT-based authentication and are passing the Bearer Authorization header to the SSE-interface by adding the header to the eventSourceInitDict parameter of the EventSourcePolyfill constructor.

However, the token might expire (as soon as after ten minutes, for security reasons).
When the token expires, our app automatically requests a new token.
However, the EventSourcePolyfill is still using the old, expired token, resulting in authentication errors.

It would be neat if we had an option to update the headers that are sent to the SSE interface, so that the new headers are used whenever the SSE-connection gets interrupted (usually after a few minutes due to timeout).
I can imagine an `update` method, taking an EventSourceInit as a parameter.

Closing the event source and creating a new one is not an option, as the lastEventId is then missing.

**Comment by sguiheux** [comment]
And if we can create a new EventSource and passing the lastEventId in the constructor it will be good  ?

**Comment by PapaNappa** [comment]
Well, that would mean I have to keep track of the lastEventId. This is already handled in the EventSource, so as a user of this library, I would wish the simplest interface without doing work that is already done by the library. :)

Another effect is that the re-connect timeout is not respected: If the connection is interrupted or the header invalid, I would like to immediately close the EventSource and create a new one. I guess the timeouts in the EventSource are there for a reason - and again, adding the timeout would be extra work for me (as a user) that is already handled by the library.

As a side note, my current work-around is to modify the headers object I passed in to the constructor (within the onerror handler). Luckily, the object is saved per reference, so I can modify it. However, the changes seem to take effect only at the second try.

        this.serverSentEventSource = new EventSourcePolyfill(sseURL, eventSourceConfig);

        // in case of errors, prepare a new request to e.g. update authentication headers
        this.serverSentEventSource.onerror = () => {
          newRequestInit = …;
          for (const [key, header] of Object.entries(newRequestInit.headers as any))
            (eventSourceConfig.headers as any)[key] = header;
        });

**Comment by sguiheux** [comment]
Could you test this branch? 
I had an upadte method that just update header for now
And there is the fix for #16 that let you catch http error on   onerror method

**Comment by PapaNappa** [comment]
Thanks, this seems to work well. :)
But I have a follow-up issue which I will open now.
