### ISSUE TITLE
creating a new EventSourcePolyfill instance with no options argument throws error

### ISSUE THREAD

**Issue by jlamfers** [sguiheux/EventSource#21]
creating a new EventSourcePolyfill instance with no options argument throws null reference error on options.heartbeatTimeout

line 155: var heartbeatTimeout = getDuration(options.heartbeatTimeout || 45000, 0);

**Comment by sguiheux** [comment]
Hi,
I will not fix that. Just put {} in constructor. I don't like optionnal argument :)
