### ISSUE TITLE
ERROR TypeError: Cannot read property 'heartbeatTimeout' of undefined

### ISSUE THREAD

**Issue by TitaneBoy** [sguiheux/EventSource#8]
Hello there..I was trying to use your package in my angular project but I got the error described in the title...

Here is the code of my SSE service

```
import { Injectable, NgZone } from '@angular/core';
import { Observable } from 'rxjs';

import {EventSourcePolyfill} from 'ng-event-source';

@Injectable()
export class SSEServices {

  constructor(private zone: NgZone) {
  }

  getSSEService(name: string) {
    switch (name) {
      case 'Resume':
        return Observable.create((observer) => {
          const eventSource = new EventSourcePolyfill('https://localhost/webclientapi/livessereadings');
          eventSource.onmessage = (event) => {
            const data = JSON.parse(event.data);
            this.zone.run(() => {
              observer.next(data);
            });
          };
          eventSource.onerror = (error) => {
            observer.error(JSON.stringify(error));
          };
          return () => eventSource.close();
        });
      default:
        break;
    }
  }

}
```

Did I miss something ?

Thank you in advance for your help :-)

**Comment by TitaneBoy** [comment]
Here is the issue I have in the Chrome console:

![image](https://user-images.githubusercontent.com/15614466/42824451-d9da33d8-89ad-11e8-9ced-5390b2c85ece.png)

**Comment by sguiheux** [comment]
Hello,

The constructor has 2 parameters, :  url and option.
If you have nothing to pass in option parameter, just send {}
=> const eventSource = new EventSourcePolyfill('
https://localhost/webclientapi/livessereadings', {});

Steven


Le mar. 17 juil. 2018 à 16:40, TitaneBoy <notifications@github.com> a
écrit :
